version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "learning_platform"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  redis:
      image: redis:latest
      restart: always
      ports:
        - "6379:6379"