CREATE_COURSE = 'INSERT INTO "course" (name, description, user_id) VALUES (%s, %s, %s) RETURNING id'
UPDATE_COURSE = 'UPDATE "course" SET name = %s, description = %s WHERE id = %s'
UPDATE_IS_ACTIVE_COURSE = 'UPDATE "course" SET is_active = %s WHERE id = %s'
DELETE_COURSE = 'DELETE FROM "course" WHERE id = %s'
SELECT_COURSES_LIST_BY_USER_ID = 'SELECT * FROM "course" WHERE user_id = %s'
SELECT_COURSE_LINKS = 'SELECT links FROM "course" WHERE id = %s'
UPDATE_COURSE_LINKS = 'UPDATE "course" SET links = %s WHERE id = %s'
SELECT_COURSE_MATEIALS = 'SELECT materials FROM "course" WHERE id = %s'
UPDATE_COURSE_MATERIALS = 'UPDATE "course" SET materials = %s WHERE id = %s'
GET_LINKS_AND_MATERIALS = 'SELECT links, materials FROM "course" WHERE id = %s'
CREATE_COURSE_USER_LINK = 'INSERT INTO "user_course" (user_id, course_id) VALUES (%s, %s)'
SELECT_COURSES_LIST = 'SELECT c.id, name, description, is_active FROM "user_course" as uc JOIN "course" as c ON uc.course_id = c.id WHERE uc.user_id = %s'
SELECT_USERS_ON_COURSE = 'SELECT u.id, u.first_name, u.second_name, u.middle_name, u.email FROM "user" as u JOIN "user_course" as uc ON uc.user_id = u.id WHERE uc.course_id = %s'
DELETE_COURSE_USER_LINK = 'DELETE FROM "user_course" WHERE user_id = %s AND course_id = %s'