openapi: 3.1.0

info:
    title: Learning Platform Admin
    description: HTTP endpoints for admins
    version: '1.0'

paths:
    /admin/user/list:
        get:
            description: Получение списка пользователей для администратора
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminUserListResponse200'
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена
    
    /admin/user/role:
        put:
            description: Изменение роли пользователя
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PutUserRoleRequest'
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                404:
                    description: Организация или пользователь не найдены

    /admin/user:
        delete:
            description: Удаление пользователя
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/UserID'
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                404:
                    description: Организация или пользователь не найдены
    
    /admin/course/list:
        get:
            description: Получение списка курсов
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CourseListResponse200'
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена

    /admin/course:
        put:
            description: Редактирование курса
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/CourseID'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CourseModel'
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена
        delete:
            description: Удаление курса
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/CourseID'
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена

components:
    parameters:
        OrganizationID:
            in: query
            name: organization_id
            description: ID организации
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        Token:
            in: query
            type: object
            name: token
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        CourseID:
            in: query
            type: object
            name: course_id
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        UserID:
            in: query
            type: object
            name: user_id
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

    schemas:
        NotEmptyString:
            type: string
            minLength: 1

        FullName:
            type: object
            required:
              - first_name
              - second_name
            properties:
                first_name:
                    description: Имя
                    $ref: '#/components/schemas/NotEmptyString'
                second_name:
                    description: Фамилия
                    $ref: '#/components/schemas/NotEmptyString'
                middle_name:
                    description: Отчество
                    $ref: '#/components/schemas/NotEmptyString'
        
        UserRole:
            type: string
            enum:
              - student
              - teacher
              - admin

        User:
            type: object
            required:
              - id
              - full_name
              - email
              - role
            properties:
                id:
                    $ref: '#/components/schemas/NotEmptyString'
                full_name:
                    $ref: '#/components/schemas/FullName'
                email:
                    $ref: '#/components/schemas/NotEmptyString'
                role:
                    $ref: '#/components/schemas/UserRole'

        Course:
            type: object
            required:
              - id
              - name
              - description
            properties:
                id:
                    $ref: '#/components/schemas/NotEmptyString'
                name:
                    $ref: '#/components/schemas/NotEmptyString'
                description:
                    $ref: '#/components/schemas/NotEmptyString'

        AdminUserListResponse200:
            type: array
            items:
                $ref: '#/components/schemas/User'
            minItems: 1
        
        PutUserRoleRequest:
            type: object
            required:
              - id
              - role
            properties:
                id:
                    $ref: '#/components/schemas/NotEmptyString'
                role:
                    $ref: '#/components/schemas/UserRole'
        
        CourseListResponse200:
            type: array
            items:
                $ref: '#/components/schemas/Course'

        CourseModel:
            type: object
            required:
              - name
              - description
            properties:
                name:
                    $ref: '#/components/schemas/NotEmptyString'
                description:
                    $ref: '#/components/schemas/NotEmptyString'