openapi: 3.1.0

info:
    title: Learning Platform Assignments
    description: HTTP endpoints for assignments
    version: '1.0'

paths:
    /assignment/teacher:
        post:
            description: Создание задания
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/CourseID'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AssignmentModel'
            responses:
                201:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AssignmentCreateResponse201'
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена
        put:
            description: Редактирование задания
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/AssignmentID'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AssignmentModel'
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена
        delete:
            description: Удаление задания
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/AssignmentID'
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена

    /assignment/list:
        get:
            description: Получить список заданий
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/CourseID'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AssignmentListResponse200'
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена

    /assignment/courses:
        get:
            description: Получение списка заданий на курсах
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AssignmentCoursesResponse200'
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена

    /assignment/student/info:
        get:
            description: Получение информации о задании для студента
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/AssignmentID'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AssignmentInfoResponse200'
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена

    /assignment/teacher/info:
        get:
            description: Получение информации о задании для студента
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/AssignmentID'
              - $ref: '#/components/parameters/UserID'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AssignmentInfoResponse200'
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена

components:
    parameters:
        OrganizationID:
            in: query
            name: organization_id
            description: ID организации
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        Token:
            in: query
            type: object
            name: token
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        CourseID:
            in: query
            type: object
            name: course_id
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        AssignmentID:
            in: query
            type: object
            name: assignment_id
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        UserID:
            in: query
            type: object
            name: user_id
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

    schemas:
        NotEmptyString:
            type: string
            minLength: 1

        AssignmentStatus:
            type: string
            enum:
              - pending
              - in_review
              - graded

        AssignmentModel:
            type: object
            required:
              - name
              - started_at
            properties:
                name:
                    $ref: '#/components/schemas/NotEmptyString'
                started_at:
                    type: datetime
                ended_at:
                    type: datetime

        AssignmentCreateResponse201:
            type: object
            required:
              - assignment_id
            properties:
                assignment_id:
                    $ref: '#/components/schemas/NotEmptyString'

        Assignment:
            type: object
            required:
              - id
              - name
              - started_at
            properties:
                id:
                    $ref: '#/components/schemas/NotEmptyString'
                name:
                    $ref: '#/components/schemas/NotEmptyString'
                started_at:
                    type: datetime
                ended_at:
                    type: datetime
                status:
                    $ref: '#/components/schemas/AssignmentStatus'
                    
        AssignmentListResponse200:
            type: array
            items:
                $ref: '#/components/schemas/Assignment'

        AssignmentCourse:
            type: object
            required:
              - course_id
              - course_name
              - assignments
            properties:
                course_id:
                    $ref: '#/components/schemas/NotEmptyString'
                course_name:
                    $ref: '#/components/schemas/NotEmptyString'
                assignments:
                    type: array
                    items:
                        $ref: '#/components/schemas/Assignment'
                    minItems: 1

        AssignmentCoursesResponse200:
            type: array
            items:
                $ref: '#/components/schemas/AssignmentCourse'

        TaskInfo:
            type: object
            required:
              - id
              - question_type
              - answer_type
            properties:
                id:
                    $ref: '#/components/schemas/NotEmptyString'
                question_type:
                    type: string
                    enum:
                      - text
                      - file
                question_text:
                    $ref: '#/components/schemas/NotEmptyString'
                question_file:
                    $ref: '#/components/schemas/NotEmptyString'
                answer_type:
                    type: string
                    enum:
                      - text
                      - file
                      - variants
                answer_variants:
                    type: array
                    items:
                        $ref: '#/components/schemas/NotEmptyString'
                    minItems: 1
                answer_text:
                    $ref: '#/components/schemas/NotEmptyString'
                answer_file:
                    $ref: '#/components/schemas/NotEmptyString'
                assessment:
                    type: int
                feedback:
                    $ref: '#/components/schemas/NotEmptyString'

        AssignmentInfoResponse200:
            type: object
            required:
              - tasks_info
            properties:
                tasks_info:
                    type: array
                    items:
                        $ref: '#/components/schemas/TaskInfo'
