openapi: 3.1.0

info:
    title: Learning Platform Courses
    description: HTTP endpoints for courses
    version: '1.0'

paths:
    /course/teacher:
        post:
            description: Создание курса
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CourseModel'
            responses:
                201:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CourseCreateResponse201'
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена
        put:
            description: Редактирование курса
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/CourseID'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CourseModel'
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена
        delete:
            description: Удаление курса
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/CourseID'
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена
    
    /course/teacher/list:
        get:
            description: Получение списка курсов
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CourseListResponse200'
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена

components:
    parameters:
        OrganizationID:
            in: query
            name: organization_id
            description: ID организации
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        Token:
            in: query
            type: object
            name: token
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'
        
        CourseID:
            in: query
            type: object
            name: course_id
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

    schemas:
        NotEmptyString:
            type: string
            minLength: 1
        
        CourseModel:
            type: object
            required:
              - name
              - description
            properties:
                name:
                    $ref: '#/components/schemas/NotEmptyString'
                description:
                    $ref: '#/components/schemas/NotEmptyString'
        
        Course:
            type: object
            required:
              - id
              - name
              - description
            properties:
                id:
                    $ref: '#/components/schemas/NotEmptyString'
                name:
                    $ref: '#/components/schemas/NotEmptyString'
                description:
                    $ref: '#/components/schemas/NotEmptyString'
        
        CourseCreateResponse201:
            type: object
            required:
              - course_id
            properties:
                course_id:
                    $ref: '#/components/schemas/NotEmptyString'
        
        CourseListResponse200:
            type: array
            items:
                $ref: '#/components/schemas/Course'