openapi: 3.1.0

info:
    title: Learning Platform Tasks
    description: HTTP endpoints for tasks
    version: '1.0'

paths:
    /task/teacher:
        post:
            description: Создание таски
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/AssignmentID'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskModel'
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                question_file:
                                    type: string
                                    format: binary
            responses:
                201:
                    description: OK
                400:
                    description: Bad Request
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена
        delete:
            description: Удаление таски
            parameters:
              - $ref: '#/components/parameters/OrganizationID'
              - $ref: '#/components/parameters/Token'
              - $ref: '#/components/parameters/TaskID'
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                404:
                    description: Организация не найдена

components:
    parameters:
        OrganizationID:
            in: query
            name: organization_id
            description: ID организации
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        Token:
            in: query
            type: object
            name: token
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        AssignmentID:
            in: query
            type: object
            name: assignment_id
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

        TaskID:
            in: query
            type: object
            name: assignment_id
            required: true
            schema:
                $ref: '#/components/schemas/NotEmptyString'

    schemas:
        NotEmptyString:
            type: string
            minLength: 1

        TaskModel:
            type: object
            required:
              - question_type
              - answer_type
            properties:
                question_type:
                    type: string
                    enum:
                      - text
                      - file
                question_text:
                    $ref: '#/components/schemas/NotEmptyString'
                answer_type:
                    type: string
                    enum:
                      - text
                      - file
                      - variants
                answer_variants:
                    type: array
                    items:
                        $ref: '#/components/schemas/NotEmptyString'
                    minItems: 1