CREATE TABLE "user" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL,
  "first_name" varchar NOT NULL,
  "second_name" varchar NOT NULL,
  "middle_name" varchar,
  "hash_password" varchar NOT NULL,
  "role" varchar NOT NULL,
  "has_confirmed_email" bool NOT NULL DEFAULT false
);

CREATE TABLE "course" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "links" jsonb,
  "materials" jsonb,
  "is_active" bool NOT NULL DEFAULT true,
  "user_id" int NOT NULL
);

CREATE TABLE "user_course" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "assignment" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "name" varchar NOT NULL,
  "started_at" timestamp NOT NULL,
  "ended_at" timestamp
);

CREATE TABLE "task" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assignment_id" int NOT NULL,
  "question_type" varchar NOT NULL,
  "question_text" varchar NOT NULL,
  "question_file" varchar NOT NULL,
  "answer_type" varchar NOT NULL,
  "answer_variants" jsonb
);

ALTER TABLE "course" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;

ALTER TABLE "user_course" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;

ALTER TABLE "user_course" ADD FOREIGN KEY ("course_id") REFERENCES "course" ("id") ON DELETE CASCADE;

ALTER TABLE "assignment" ADD FOREIGN KEY ("course_id") REFERENCES "course" ("id") ON DELETE CASCADE;

ALTER TABLE "task" ADD FOREIGN KEY ("assignment_id") REFERENCES "assignment" ("id") ON DELETE CASCADE;